"""Generate docs/cycle-time-evidence.md from THIS repo's real git history.

Only data git actually holds is used: commit author timestamps, subjects and
trailers. Nothing is estimated. Regenerate any time with:

    python scripts/cycle_time_from_git.py > docs/cycle-time-evidence.md
"""

from __future__ import annotations

import subprocess  # noqa: S404 - fixed git command, no shell
import sys
from datetime import datetime, timedelta, timezone

SGT = timezone(timedelta(hours=8))

SEP = "\x1f"
FORMAT = SEP.join(["%h", "%aI", "%s", "%(trailers:key=AI-Assisted,valueonly,separator=;)"])


def git_log(ref: str = "HEAD") -> list[dict]:
    out = subprocess.run(  # noqa: S603
        ["git", "log", "--reverse", f"--format={FORMAT}", ref],  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    rows = []
    for line in out.splitlines():
        sha, when, subject, ai = line.split(SEP)
        rows.append(
            {"sha": sha, "when": datetime.fromisoformat(when), "subject": subject, "ai": ai.strip()}
        )
    return rows


def fmt_delta(delta: timedelta | None) -> str:
    if delta is None:
        return "-"
    minutes = int(delta.total_seconds() // 60)
    return f"{minutes // 60} h {minutes % 60:02d} min" if minutes >= 60 else f"{minutes} min"


def render(rows: list[dict]) -> str:
    lines = [
        "# Cycle-time evidence: real timestamps from this repo",
        "",
        "> Generated by `scripts/cycle_time_from_git.py` from `git log`. **Every number below"
        " comes from git metadata in this repository.** Nothing is estimated or copied from"
        " elsewhere.",
        "",
        f"Generated at commit `{rows[-1]['sha'] if rows else '-'}`. The commit that adds or"
        " refreshes this page comes after it, so it is not listed.",
        "",
        "| # | Commit | Author time (SGT) | Since previous commit | AI-Assisted | Subject |",
        "|---|---|---|---|---|---|",
    ]
    prev = None
    for i, r in enumerate(rows, 1):
        delta = r["when"] - prev if prev else None
        stamp = r["when"].astimezone(SGT).strftime("%Y-%m-%d %H:%M")
        subject = r["subject"].replace("|", "/")
        lines.append(
            f"| {i} | `{r['sha']}` | {stamp} | {fmt_delta(delta)} | {r['ai'] or '-'} | {subject} |"
        )
        prev = r["when"]
    if rows:
        span = rows[-1]["when"] - rows[0]["when"]
        lines += [
            "",
            f"**Span from first to last commit:** {fmt_delta(span)} across {len(rows)} commits.",
        ]
    lines += [
        "",
        "## How to read this (and what it does NOT show)",
        "- **What it shows:** when each change was committed. Author times are kept"
        " when commits are re-authored, so they are the real times.",
        "- **Gaps measure commit spacing, not effort.** Commits made in one batch after the"
        " files were written show ~0 min. Waiting time, such as waiting for an approval,"
        " shows up as a long gap.",
        "- **What it leaves out:** time spent writing briefs, human thinking time, and the"
        " review time in `docs/review-log.md`. Git does not record these.",
        "- **No before/after claim.** There is no baseline from the same team doing the same"
        " work without the harness. With n = 1 project, the honest comparison result is"
        " *not enough data*. Use [cycle-time-template.md](cycle-time-template.md) to collect"
        " both sides on real work.",
        "- **Built by an AI agent in one sitting.** These times reflect an agent-built demo."
        " They are not a benchmark for client projects.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":  # pragma: no cover
    sys.stdout.write(render(git_log(sys.argv[1] if len(sys.argv) > 1 else "HEAD")))
