"""Regenerate the SYNTHETIC fixtures in fixtures/ (deterministic, seed=42).

The values are invented to look plausible for Singapore (tropical, ~24-33 degC);
they are NOT real observations and must not be quoted as weather data.
Deliberate defects are injected so the quality checks have something to find.
"""

from __future__ import annotations

import csv
import json
import random
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "fixtures"
HEADER = [
    "DATE",
    "STATION",
    "DAILY_RAINFALL_TOTAL",
    "HIGHEST_30_MIN_RAINFALL",
    "HIGHEST_60_MIN_RAINFALL",
    "HIGHEST_120_MIN_RAINFALL",
    "MEAN_TEMPERATURE",
    "MAXIMUM_TEMPERATURE",
    "MINIMUM_TEMPERATURE",
    "MEAN_WIND_SPEED",
    "MAX_WIND_SPEED",
]


def daily_rows() -> list[list[str]]:
    rng = random.Random(42)
    rows = []
    start = date(2016, 12, 18)
    for i in range(28):
        day = start + timedelta(days=i)
        if day == date(2016, 12, 25):  # injected defect: date gap
            continue
        rain = max(0.0, round(rng.gauss(6, 8), 1))
        h30 = round(min(rain, rain * rng.uniform(0.3, 0.7)), 1)
        h60 = round(min(rain, h30 * 1.3), 1)
        h120 = round(min(rain, h60 * 1.2), 1)
        tmax = round(rng.uniform(29.5, 33.5), 1)
        tmin = round(rng.uniform(23.5, 26.0), 1)
        tmean = round((tmax + tmin) / 2 + rng.uniform(-0.4, 0.4), 1)
        wmean = round(rng.uniform(4, 12), 1)
        wmax = round(wmean + rng.uniform(15, 30), 1)
        row = [
            day.isoformat(),
            "Synthetic Station A",
            rain,
            h30,
            h60,
            h120,
            tmean,
            tmax,
            tmin,
            wmean,
            wmax,
        ]
        rows.append([str(v) for v in row])
    rows[3][3] = "na"  # injected defect: missing values, as in the raw source
    rows[3][4] = "na"
    rows[10][7] = "na"
    rows[15][8], rows[15][7] = rows[15][7], rows[15][8]  # injected: min > max
    rows.insert(6, list(rows[6]))  # injected defect: duplicate date
    return rows


def realtime_payload() -> dict:
    # Shape mirrors the live v2 air-temperature response (checked 2026-10-01).
    stations = [
        ("SYN01", "Synthetic Station North", 1.42, 103.82),
        ("SYN02", "Synthetic Station East", 1.35, 103.98),
        ("SYN03", "Synthetic Station West", 1.33, 103.70),
    ]
    return {
        "code": 0,
        "errorMsg": "",
        "data": {
            "stations": [
                {
                    "id": sid,
                    "deviceId": sid,
                    "name": name,
                    "location": {"latitude": lat, "longitude": lon},
                }
                for sid, name, lat, lon in stations
            ],
            "readings": [
                {
                    "timestamp": "2026-01-15T14:00:00+08:00",
                    "data": [
                        {"stationId": "SYN01", "value": 31.2},
                        {"stationId": "SYN02", "value": 30.4},
                        {"stationId": "SYN03", "value": 32.0},
                    ],
                },
                {
                    "timestamp": "2026-01-15T14:01:00+08:00",
                    "data": [
                        {"stationId": "SYN01", "value": 31.3},
                        {"stationId": "SYN02", "value": 30.5},
                    ],
                },
            ],
            "readingType": "DBT 1M F",
            "readingUnit": "deg C",
        },
        "_note": "SYNTHETIC fixture - invented values in the public API's shape.",
    }


def main() -> None:
    ROOT.mkdir(exist_ok=True)
    with open(ROOT / "daily_weather_synthetic.csv", "w", newline="", encoding="utf-8") as f:
        f.write("# SYNTHETIC DATA - generated by scripts/make_fixtures.py; not real observations\n")
        writer = csv.writer(f)
        writer.writerow(HEADER)
        writer.writerows(daily_rows())
    with open(ROOT / "realtime_air_temperature_synthetic.json", "w", encoding="utf-8") as f:
        json.dump(realtime_payload(), f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    main()
